on:
  workflow_dispatch:
  push:
    tags:
      - "*"

name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
          working-directory: extension
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install project dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm test
          working-directory: extension

      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          packagepath: extension
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
